// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxRx-9EtDkHCvICE8FyBD2NaU0CA7_DXM',
    appId: '1:210087565710:web:e817b7917ef402cdd8ecdf',
    messagingSenderId: '210087565710',
    projectId: 'prescribr-4aa4f',
    authDomain: 'prescribr-4aa4f.firebaseapp.com',
    storageBucket: 'prescribr-4aa4f.firebasestorage.app',
    measurementId: 'G-PZL5TSC7EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbtOTPy7NNf6mFjYs3clqREkfSipwyRpA',
    appId: '1:210087565710:android:6a58eb088b40a653d8ecdf',
    messagingSenderId: '210087565710',
    projectId: 'prescribr-4aa4f',
    storageBucket: 'prescribr-4aa4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRFE4OzK4hGqz0s75D2MT5kU_K1RM0i7w',
    appId: '1:210087565710:ios:512b1106b525e4bdd8ecdf',
    messagingSenderId: '210087565710',
    projectId: 'prescribr-4aa4f',
    storageBucket: 'prescribr-4aa4f.firebasestorage.app',
    iosBundleId: 'ca.prescribr.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRFE4OzK4hGqz0s75D2MT5kU_K1RM0i7w',
    appId: '1:210087565710:ios:512b1106b525e4bdd8ecdf',
    messagingSenderId: '210087565710',
    projectId: 'prescribr-4aa4f',
    storageBucket: 'prescribr-4aa4f.firebasestorage.app',
    iosBundleId: 'ca.prescribr.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxRx-9EtDkHCvICE8FyBD2NaU0CA7_DXM',
    appId: '1:210087565710:web:0e4a260dcf0edf89d8ecdf',
    messagingSenderId: '210087565710',
    projectId: 'prescribr-4aa4f',
    authDomain: 'prescribr-4aa4f.firebaseapp.com',
    storageBucket: 'prescribr-4aa4f.firebasestorage.app',
    measurementId: 'G-EFWQFPPD6R',
  );
}
